### ISSUE TITLE
[Number Input] Issue - SolidJS max breaks when setting value to max

### ISSUE THREAD

**Issue by codylindley** [chakra-ui/zag#1391]
### Description

When setting the value to the max value when using the solidjs number input the increment button becomes broken after you decrement. This occurs when setting the value to the min value as well. Works fine as long as the inital value does not match the min or max value.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/solidjs-templates-til9wr?file=src%2FApp.tsx

### Steps to Reproduce

(based off the stackblitz I linked)

1. decrement
2. then try to increment (the increment button is none responsive)

### Ark UI Version

2.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

### Browser

Edge

**Comment by segunadebayo** [comment]
Thanks for reporting this, @codylindley.

I appreciate the triage, @cschroeter. After looking through this, it turns out it's related to the mergeProps implementation we had, which relied on Proxy implementation and sometimes got buggy.

I rewrote the implementation to use a simpler logic and work consistently across all frameworks. [See Commit](https://github.com/chakra-ui/zag/commit/198f5253a09eac721c5bae9e468588f9d93ea7bb)

We'll release an update for Zag.js shortly, which will be upstreamed to Ark 3.0.

If the issue persists after upgrading, I'll re-open it.

**Comment by cschroeter** [comment]
@segunadebayo  Rockstar
