### ISSUE TITLE
Certain ColorPicker Channel Inputs Not Clamping

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/zag#1567]
### Description

The ColorPicker.ChannelInput component for certain channels does not clamp the value on blur. 

So far only Alpha, Hex, Red, Green, and Blue are clamped. Hue, Saturation, Brightness and Lightness are not clamped.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-mylluo?file=src%2FApp.tsx

### Steps to Reproduce

1. Edit Hue, Saturation, or Brightness input value to a very large number.
2. Blur the input
3. See that the input value does not clamp.

### Ark UI Version

3.20

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by cschroeter** [comment]
@elson-currentcorp 

Thanks for reporting the issue. I can confirm the issue.

@segunadebayo 

Is this something we want to support?

**Comment by segunadebayo** [comment]
We can do a better job in the docs, but it doesn't work because the machine needs to know the active format of the color.

Hex codes are converted to RGBA internally, which is why RGBA works. If you set `format=hsla`, the HSLA inputs will work as expected.

Ideally, you only want to show inputs that match the current format or control the format using a select element. See a tool like Figma for example.

![CleanShot 2024-06-07 at 19 18 36@2x](https://github.com/chakra-ui/zag/assets/6916170/767f12b6-a43f-4d1e-86d5-64383ece4330)
