### ISSUE TITLE
Closing a popover programmatically does not return focus to trigger

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1788]
# 🐛 Bug report

Changing the `open state` to false does not return focus to the popover trigger.

## 💥 Steps to reproduce

1. Tab to the popover trigger. Press it
2. Press the action button. Focus is not on popover trigger.

## 💻 Link to reproduction

https://codesandbox.io/p/sandbox/controlled-popover-focus-trigger-issue-cl84lj

## 🧐 Expected behavior

Popover trigger should regain focus

## 🧭 Possible Solution
Could `restoreFocus` maybe fallback to true? 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.65.1          |
| Browser          |  Firefox          |
| Operating System | MacOS           |

**Comment by segunadebayo** [comment]
I pushed a fix for this.  Indeed, refactoring the code to set `restoreFocus` for most events works.

**Comment by elson-currentcorp** [comment]
@segunadebayo 

Could we expose a restoreFocus boolean prop that the user can change instead of forcing it to always be true for the Popover component? The Dialog component has this but the Popover component doesn't.

Version 3.11.0 which introduces this change actually breaks the interaction where switching between multiple popovers

**3.10.0 Behavior:**
Popover 1 is open
Click on Popover 2
Popover 1 closes
Popover 2 opens

**3.11.0 Behavior**
Popover 1 is open
Click on Popover 2
Popover 1 closes
Popover 2 opens
Popover 1 restores focus to trigger
Popover 2 closes
Popover 2 restores focus to trigger
