### ISSUE TITLE
<Collapsible> flashes when moved as list items

### ISSUE THREAD

**Issue by du33169** [chakra-ui/zag#2138]
### Description

I have a list of items, each using a Collapsible to toggle show/hide with animation.
The collapse state of all items are controlled by a single boolean flag.
If I change the order of the items, their collapsibles will flash (a quick toggle) even if the flag is not changed.

It should also be noted that when the page is first loaded, clicking the reverse button will swap them normally;
But if you toggle the collapse state and back again, it will flash at next reverse.

|   expected   |  actually    |
| ---- | ---- |
|   ![noflash](https://github.com/user-attachments/assets/72006731-a4dd-456a-83d9-7fac3cd4f1c4)   |      ![flash](https://github.com/user-attachments/assets/45c6b9d8-d031-4950-a55a-27c12bd247a0)|

### Link to Reproduction

https://stackblitz.com/edit/chakra-ui-v3-ib5zi6pl

### Steps to reproduce

1. Go to the Reproduction Project
2. Click 'Reverse' (the elements will be swapped as normal)
3. Click 'toggle collapse' **twice**.
4.  Click on 'reverse' again (items will be swapped but with flash)

### Chakra UI Version

3.2.2

### Browser

Mozilla Firefox v133.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I transferred this issue to Zag.js where it'll be fixed.

**Comment by segunadebayo** [comment]
After debugging this issue a bit more. The problem seems to be with the `key` prop passed to the `Card`

Each time the `value` is changed, React destroys and re-creates the nodes which kicks off the entry animation which leads to the flash.

Changing to a stable key or `id` from an object should fix this.

I've used `index` in this example to resolve this.

```tsx
<HStack>
          {list.map((value, index) => (
            <MyCard key={index} value={value} open={open} />
          ))}
</HStack>
```

https://stackblitz.com/edit/chakra-ui-v3-9nhum9hv?file=src%2FApp.tsx

**Comment by segunadebayo** [comment]
I found an alternative solution for this and pushed the fix.

We'll release an update shortly
