### ISSUE TITLE
Context Menu change place when window scroll

### ISSUE THREAD

**Issue by oSethoum** [chakra-ui/zag#592]
# 🐛 Bug report

https://user-images.githubusercontent.com/88779394/229523780-7e88bb35-95d3-440e-9283-e5920fbd7c46.mp4

## 💥 Steps to reproduce

1. Go to context menu [docs](https://zagjs.com/components/context-menu)
2. Scroll a bit.
3. Right click on Open context menu box.
4. See the problem.

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    Docs version    |
| Browser          | Chrome / Edge   |
| Operating System |  Ubuntu / Windows 10  |

**Comment by segunadebayo** [comment]
Hi @oSethoum,

This is only a bug on the website showcase due to the underlying MDX framework (contentlayer). It works in an actual application. Unfortunately, there's not much we can do about it.

We'll implement a modal version of the menu that blocks the scroll when the menu is open to prevent issues like these in the future.
