### ISSUE TITLE
[mobile][dialog][select] Select dropdown not opening if inside a dialog from mobile (touch)

### ISSUE THREAD

**Issue by Giamme** [chakra-ui/zag#763]
# 🐛 Bug report

Using the select component inside a dialog component works fine on desktops but it doesn't behave correctly.
On mobile (I've been able to test only on iOS for now) it seems like the dropdown never opens after pressing the select button but in reality, it opens and quickly closes (probably sending another touch event right after the opening of the dropdown). I've been able to catch the dropdown quickly opening and then closing with the browser profiler.

## 💥 Steps to reproduce

1. Put a Select component inside a Dialog
2. Open on a mobile device
3. Open the dialog then tap the select button
4. The select dropdown never(?) opens up

## 💻 Link to reproduction

CodeSandbox reproduction: [https://codesandbox.io/p/sandbox/wizardly-yonath-zc683j?file=%2Fsrc%2Fcomponents%2FTooltip.vue%3A15%2C1](https://codesandbox.io/p/sandbox/wizardly-yonath-zc683j?file=%2Fsrc%2Fcomponents%2FTooltip.vue%3A15%2C1)

## 🧐 Expected behavior

The select dropdown opens just fine when inside a dialog

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |       0.12.0     |
| Browser          |      Safari iOS      |
| Operating System |     iOS 16.2       |

## 📝 Additional information

Use the profiler and record the opening action to be able to catch when the dropdown opens and when it closes back again.

<img width="1287" alt="Screenshot 2023-07-24 alle 13 16 58" src="https://github.com/chakra-ui/zag/assets/39541140/3221d393-f5f2-4810-a907-8f3853be34f9">

**Comment by segunadebayo** [comment]
After some investigation, it seems related to focus trapping and the fact the select is teleported.

If you disabled the Teleport for the select, it should work fine.

Looking to find a way to handle this internally, or else we'll document how to manage these scenarios.

**Comment by segunadebayo** [comment]
The solution is avoiding Teleport when the component is within a dialog. You can design a "portalled" prop to control this use case.

This works because the focus trap needs to consider the select's trigger and content as part of the dialog so it doesn't aggressively hijack the focus back into the dialog.

![CleanShot 2023-08-24 at 12 29 58@2x](https://github.com/chakra-ui/zag/assets/6916170/c2c05be7-149d-4089-ade6-ad325b9c405c)

I'll update the docs to include this tip.

Here's the sandbox:
https://codesandbox.io/p/sandbox/wizardly-yonath-zc683j?file=%2Fsrc%2Fcomponents%2FTooltip.vue%3A15%2C1
