### ISSUE TITLE
Overlay components force the use of z-index: auto

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/zag#981]
# 🐛 Bug report

Hi!

In the latest versions of Zag.js, there are some changes that force a `z-index: auto` when using `api.positionerProps` on overlay components (Select, Menu, etc.) which can cause some issues with stacking context.

## 💥 Steps to reproduce

1. Go to this [codesandbox](https://codesandbox.io/s/dazzling-dubinsky-4vlp8c)
2. Click on the Select
3. See that the content of Select is overlapped even if it's rendered within a Portal

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/dazzling-dubinsky-4vlp8c

## 🧐 Expected behavior

The content of the Select should be displayed on top of the green box.

## 🧭 Possible Solution

Until now, I used to define manually the stacking level (`z-index`) of the positioner but, I can't anymore since it's overrided by Zag.js. I can use the `!important` CSS syntax but it feels wrong.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.27.1          |
| Browser          |  Google Chrome 118          |
| Operating System |  Linux Ubuntu  22.04        |

**Comment by samadadi** [comment]
you can use `mergeProps` from `@zag-js/react` to merge your custom props object that has a style object as a property with `api.positionerProps`. This is a better way. For example: `mergeProps(api.positionerProps, {style: {zIndex: 50}})`

**Comment by fseglard** [comment]
@samadadi As a consumer of ArkUI (which use Zag.js), I cannot do that directly but thanks for the workaround anyway.

What is the reason behind the addition of `z-index: auto` on the Zag.js side?

**Comment by samadadi** [comment]
> As a consumer of ArkUI (which use Zag.js), I cannot do that directly but thanks for the workaround anyway.

ArkUI does this for you itself. You just pass `<Combobox.Positioner style={{zIndex: 50}}>...`. [https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/src/combobox/combobox-positioner.tsx#L11](https://github.com/chakra-ui/ark/blob/main/packages/frameworks/react/src/combobox/combobox-positioner.tsx#L11)

> What is the reason behind the addition of `z-index: auto` on the Zag.js side?

First because the default value of `z-index` is `auto` even without setting that explicitly. Second `z-index` value is depends on user's preference. [https://stackoverflow.com/questions/7911311/what-is-default-z-index-of-div-element-in-html-and-how-to-get-it-using-javasc](https://stackoverflow.com/questions/7911311/what-is-default-z-index-of-div-element-in-html-and-how-to-get-it-using-javasc)

**Comment by fseglard** [comment]
Damn, I miss that for ArkUI, many thanks!

So, if that's the desired behavior for Zag.js, we can close this issue.

**Comment by Hugos68** [comment]
Any reason why this doesn't work using tailwind classes? doing `style="z-index: 20;"` works but `class="z-20"` doesn't. When doing it with Tailwind, zag's takes presedence and applies `auto`.
